apiVersion: v2
name: fiter-app
description: Sample Application

type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: fiter-base-apps
    version: '0.0.6'
    alias: community-app
    repository: "oci://public.ecr.aws/p4j9q0b3"
  - name: fiter-base-apps
    version: '0.0.6'
    alias: fineract
    repository: "oci://public.ecr.aws/p4j9q0b3"
