name: Make Manual Image Deployment to ECR

on:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: Production'
        options: ['Manual Deployment']
        required: true
        default: 'Manual Deployment'
      image-tag:
        description: 'Image tag that should be deployed'
        required: true

jobs:

  deploy:

    name: Deploy image to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: kamiazya/setup-graphviz@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_MONI_AFRICA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_MONI_AFRICA }}
          aws-region: us-east-1

      - name: installing dependcies
        run: |
          archtype=$(dpkg --print-architecture)
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$archtype/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$archtype/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl



      - name: updating kubeconfig and helm repo
        run: |
          aws eks --region us-east-1 update-kubeconfig --name moni-africa-prod
          helm repo add fiter-apps https://chartmuseum.fiter.io/ --username ${{ secrets.CHARTMUSEUM_USERNAME }} --password ${{ secrets.CHARTMUSEUM_PASSWORD }}

      - name: deploy backend
        env:
          IMAGE_TAG: ${{ github.event.inputs.image-tag }}
          FINERACT_CONTENT_S3_BUCKET_NAME: ${{ secrets.FINERACT_CONTENT_S3_BUCKET_NAME_PROD }}
          FINERACT_CONTENT_S3_REGION: ${{ secrets.FINERACT_CONTENT_S3_REGION_PROD }}
          FINERACT_CONTENT_S3_ACCESS_KEY: ${{ secrets.FINERACT_CONTENT_S3_ACCESS_KEY_PROD }}
          FINERACT_CONTENT_S3_SECRET_KEY: ${{ secrets.FINERACT_CONTENT_S3_SECRET_KEY_PROD }}
        run: |
          cd helm
          sed -i 's|FINERACT_CONTENT_S3_BUCKET_NAME:.*|FINERACT_CONTENT_S3_BUCKET_NAME: '"$FINERACT_CONTENT_S3_BUCKET_NAME"'|' values.yaml
          sed -i 's|FINERACT_CONTENT_S3_REGION:.*|FINERACT_CONTENT_S3_REGION: '"$FINERACT_CONTENT_S3_REGION"'|' values.yaml
          sed -i 's|FINERACT_CONTENT_S3_ACCESS_KEY:.*|FINERACT_CONTENT_S3_ACCESS_KEY: '"$FINERACT_CONTENT_S3_ACCESS_KEY"'|' values.yaml
          sed -i 's|FINERACT_CONTENT_S3_SECRET_KEY:.*|FINERACT_CONTENT_S3_SECRET_KEY: '"$FINERACT_CONTENT_S3_SECRET_KEY"'|' values.yaml
          kubectl config set-context --current --namespace=application
          helm dependency update
          helm upgrade -i backend --set fineract-rest.tag=$IMAGE_TAG .
                 
         
